variable "LAMBDA_INGEST_CUSTOMER_BILLING_DATA_NAME" {}
variable "LAMBDA_INGEST_CUSTOMER_CLOUDTRAIL_DATA_NAME" {}
variable "LAMBDA_INGEST_CUSTOMER_CONFIG_DATA_NAME" {}
variable "LAMBDA_INGEST_CUSTOMER_GUARDDUTY_DATA_NAME" {}
variable "LAMBDA_INGEST_CUSTOMER_CLOUDWATCH_LOGS_DATA_NAME" {}
variable "LAMBDA_INGEST_CUSTOMER_ORGANIZATION_DATA_NAME" {}
variable "LAMBDA_INGEST_CUSTOMER_SECURITYHUB_DATA_NAME" {}

variable "RESOURCE_PREFIX" {}

variable "INGEST_CUSTOMER_BILLING_DATA_TRIGGER_FREQUENCY" {}
variable "INGEST_CUSTOMER_CLOUDTRAIL_DATA_TRIGGER_FREQUENCY" {}
variable "INGEST_CUSTOMER_CONFIG_DATA_TRIGGER_FREQUENCY" {}
variable "INGEST_CUSTOMER_GUARDDUTY_DATA_TRIGGER_FREQUENCY" {}
variable "INGEST_CUSTOMER_ORGANIZATION_DATA_TRIGGER_FREQUENCY" {}
variable "INGEST_CUSTOMER_CLOUDWATCH_LOGS_DATA_TRIGGER_FREQUENCY" {}
variable "INGEST_CUSTOMER_SECURITYHUB_DATA_TRIGGER_FREQUENCY" {}


variable "LAMBDA_INGEST_CUSTOMER_BILLING_DATA_ARN" {}
variable "LAMBDA_INGEST_CUSTOMER_CLOUDTRAIL_DATA_ARN" {}
variable "LAMBDA_INGEST_CUSTOMER_CONFIG_DATA_ARN" {}
variable "LAMBDA_INGEST_CUSTOMER_GUARDDUTY_DATA_ARN" {}
variable "LAMBDA_INGEST_CUSTOMER_CLOUDWATCH_LOGS_DATA_ARN" {}
variable "LAMBDA_INGEST_CUSTOMER_ORGANIZATION_DATA_ARN" {}
variable "LAMBDA_INGEST_CUSTOMER_SECURITYHUB_DATA_ARN" {}
