
variable "DYNAMO_DB_ONBOARDING_TABLE_NAME" {}
variable "DYNAMO_DB_CUSTOMER_TABLE_NAME" {}
variable "DYNAMO_DB_LAMBDA_OPERATION_LOGS_TABLE_NAME" {}
variable "ONBOARDING_BUCKET_NAME" {}

variable "LAMBDA_ROLE_NAME" {}
variable "RESOURCE_PREFIX" {}
variable "CURRENT_ACCOUNT_ID" {}
variable "IAM_ASSUMABLE_ROLE_NAME" {}
variable "AWS_DATA_INGESTION_DESTINATION_BUCKET_NAME" {}
